version: "3"

services:

  redis:
    image: "redis:4-alpine"
    expose:
      - "6379"
    networks:
      - "example"
    volumes:
      - "redisdata:/data"
    
  hellogo:
    build: "./hellogo"
    image: "my/hellogo:1.0"
    networks:
      - "example"
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      REDISHOST: "redis"
      REDISPORT: "6379"
      REDISDB: "0"

  hellonode:
    build: "./hellonode"
    image: "my/hellonode:0.1"
    networks:
      - "example"
    expose:
      - "8080"

networks:
  example:

volumes:
  redisdata:

